const DATE_RE = /^(\d{2}\/\d{2}\/\d{2})\s+(.+)$/;
const AMOUNT_RE = /-?\d{1,3}(?:,\d{2,3})*(?:\.\d{2})|-?\d+\.\d{2}/g;

const SKIP_PATTERNS = [
  /^page\s*no/i,
  /^statement of account/i,
  /^statement summary/i,
  /^hdfc bank/i,
  /^joint holders/i,
  /^nomination/i,
  /^statement from/i,
  /^account branch/i,
  /^address\s*:/i,
  /^city\s*:/i,
  /^state\s*:/i,
  /^phone no/i,
  /^od limit/i,
  /^email\s*:/i,
  /^cust id/i,
  /^account no/i,
  /^a\/c open/i,
  /^account status/i,
  /^rtgs\/neft/i,
  /^branch code/i,
  /^account type/i,
  /^\*closing balance/i,
  /^contents of this statement/i,
  /^state account branch/i,
  /^registered office/i,
  /^generated on/i,
  /^generated by/i,
  /^requesting branch/i,
  /^this is a computer generated/i,
  /^opening balance/i,
  /^--\s*\d+\s+of\s+\d+\s*--/,
  /^date\s+narration/i,
  /^mr\s+/i,
  /^ms\s+/i,
  /^mrs\s+/i,
  /^no\s+\d/i,
  /^salem$/i,
  /^mettur/i,
  /^tamil nadu/i,
  /^this statement/i,
];

const STOP_PATTERNS = [
  /statement summary/i,
  /\*\*\*\s*end of statement/i,
];

function shouldSkip(line) {
  const trimmed = line.trim();
  if (!trimmed) return true;
  return SKIP_PATTERNS.some((re) => re.test(trimmed));
}

function parseAmounts(segment) {
  const matches = segment.match(AMOUNT_RE) || [];
  return matches.map((m) => Number(m.replace(/,/g, '')));
}

function classifyAmount(narration, amount, prevBalance, balance) {
  const upper = narration.toUpperCase();
  const creditHints = [
    /\bCR[- ]/,
    /FUNDS TRANSFER CR/,
    /NEFT CR/,
    /IMPS.*CR/,
    /UPI.*CR/,
    /\bCREDITED\b/,
    /SALARY/,
    /INTEREST\s+PAID/,
    /INTEREST\s+CREDIT/,
  ];
  const debitHints = [
    /\bDR[- ]/,
    /NEFT DR/,
    /RTGS DR/,
    /IMPS.*DR/,
    /WITHDRAWAL/,
    /CHARGES/,
    /INTEREST\s+DEBIT/,
    /\bDEBITED\b/,
  ];

  if (creditHints.some((re) => re.test(upper))) {
    return { withdrawal: null, deposit: amount };
  }
  if (debitHints.some((re) => re.test(upper))) {
    return { withdrawal: amount, deposit: null };
  }

  if (prevBalance !== null && Number.isFinite(prevBalance) && Number.isFinite(balance)) {
    const delta = Number((balance - prevBalance).toFixed(2));
    if (Math.abs(delta - amount) < 0.02) {
      return { withdrawal: null, deposit: amount };
    }
    if (Math.abs(delta + amount) < 0.02) {
      return { withdrawal: amount, deposit: null };
    }
    return delta >= 0
      ? { withdrawal: null, deposit: amount }
      : { withdrawal: amount, deposit: null };
  }

  // Default for first row when balance is negative after amount: treat as withdrawal
  return balance < 0 || upper.includes('DR')
    ? { withdrawal: amount, deposit: null }
    : { withdrawal: null, deposit: amount };
}

/**
 * Parse HDFC bank statement text into transaction rows.
 */
export function parseHdfcStatement(text) {
  const lines = text.split(/\r?\n/).map((l) => l.replace(/\s+/g, ' ').trim());
  const rows = [];
  let current = null;
  let prevBalance = null;

  const flush = () => {
    if (!current) return;

    const amounts = parseAmounts(current.amountSegment || '');
    if (amounts.length >= 2) {
      const balance = amounts[amounts.length - 1];
      const txnAmount = amounts[amounts.length - 2];
      const { withdrawal, deposit } = classifyAmount(
        current.narration,
        txnAmount,
        prevBalance,
        balance,
      );

      const narration = current.narration
        .replace(/STATEMENT SUMMARY.*/i, '')
        .replace(/Generated On:.*/i, '')
        .replace(/\s+/g, ' ')
        .trim();

      rows.push({
        date: current.date,
        narration,
        refNo: current.refNo,
        valueDate: current.valueDate,
        withdrawal,
        deposit,
        closingBalance: balance,
      });
      prevBalance = balance;
    }
    current = null;
  };

  for (const raw of lines) {
    if (STOP_PATTERNS.some((re) => re.test(raw))) {
      flush();
      break;
    }
    if (shouldSkip(raw)) {
      if (current?.amountSegment) flush();
      continue;
    }

    const dateMatch = raw.match(DATE_RE);
    if (dateMatch) {
      flush();

      const date = dateMatch[1];
      const rest = dateMatch[2];

      // Prefer trailing: <ref> <valueDate> <amounts...>
      const trailing = rest.match(
        /^(.*?)\s+([A-Z0-9][A-Z0-9\-\/]{5,})\s+(\d{2}\/\d{2}\/\d{2})\s+(.+)$/i,
      );

      if (trailing) {
        current = {
          date,
          narration: trailing[1].trim(),
          refNo: trailing[2].trim(),
          valueDate: trailing[3],
          amountSegment: trailing[4],
        };
      } else {
        // Incomplete first line — collect narration until amounts appear later
        const soft = rest.match(/^(.*?)\s+(\d{2}\/\d{2}\/\d{2})\s+(.+)$/);
        if (soft && parseAmounts(soft[3]).length >= 2) {
          current = {
            date,
            narration: soft[1].trim(),
            refNo: '',
            valueDate: soft[2],
            amountSegment: soft[3],
          };
        } else {
          current = {
            date,
            narration: rest,
            refNo: '',
            valueDate: date,
            amountSegment: '',
          };
        }
      }
      continue;
    }

    if (!current) continue;

    // Continuation / delayed amount lines
    const contAmounts = parseAmounts(raw);
    const valueDateInline = raw.match(/(\d{2}\/\d{2}\/\d{2})\s+(.+)$/);

    if (!current.amountSegment && valueDateInline && contAmounts.length >= 2) {
      // e.g. ref + value date + amounts on a later line
      const before = raw.slice(0, valueDateInline.index).trim();
      const maybeRef = before.match(/([A-Z0-9][A-Z0-9\-\/]{5,})$/i);
      if (maybeRef) {
        current.refNo = maybeRef[1];
        current.narration = `${current.narration} ${before
          .slice(0, maybeRef.index)
          .trim()}`.trim();
      } else {
        current.narration = `${current.narration} ${before}`.trim();
      }
      current.valueDate = valueDateInline[1];
      current.amountSegment = valueDateInline[2];
    } else if (!current.amountSegment && contAmounts.length >= 2) {
      current.amountSegment = raw;
    } else if (current.amountSegment) {
      // Keep post-amount narration fragments, but drop footer noise
      if (/statement summary|generated on|opening balance|dr count|cr count/i.test(raw)) {
        flush();
        break;
      }
      current.narration = `${current.narration} ${raw}`.trim();
    } else {
      // Still building narration / ref
      const refOnly = raw.match(/^([A-Z0-9][A-Z0-9\-\/]{8,})$/i);
      if (refOnly && !current.refNo) {
        current.refNo = refOnly[1];
      } else {
        current.narration = `${current.narration} ${raw}`.trim();
      }
    }
  }

  flush();
  return rows;
}

export const HDFC_COLUMNS = [
  { key: 'date', header: 'Date' },
  { key: 'narration', header: 'Narration' },
  { key: 'refNo', header: 'Chq./Ref.No.' },
  { key: 'valueDate', header: 'Value Date' },
  { key: 'withdrawal', header: 'Withdrawal Amt.' },
  { key: 'deposit', header: 'Deposit Amt.' },
  { key: 'closingBalance', header: 'Closing Balance' },
];
